# Generated by Django 5.0.2 on 2024-03-16 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('brithday', models.DateField()),
                ('gender', models.BooleanField(default=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('insurance_info', models.TextField()),
                ('personal_photo', models.ImageField(null=True, upload_to='photo/personal/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest_photo', models.ImageField(default='None', upload_to='photo/chest/%y/%m/%d')),
                ('classification', models.CharField(default='None', editable=False, max_length=50)),
                ('pneumonia', models.BooleanField(default=True, editable=False)),
                ('died', models.BooleanField(default=False)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField()),
                ('patient_type', models.PositiveSmallIntegerField(choices=[(1, 'Returned Home'), (2, 'Hospitalization')], default=2)),
                ('usmr', models.PositiveSmallIntegerField(choices=[(1, 'First Level'), (2, 'Second Level'), (3, 'Third Level')], default=1)),
                ('medical_unit', models.CharField(default='National Health System', max_length=100)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('pregnancy', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('copd', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('inmsupr', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('cardiovascular', models.BooleanField(default=False)),
                ('renal_chronic', models.BooleanField(default=False)),
                ('obesity', models.BooleanField(default=False)),
                ('tobacco', models.BooleanField(default=False)),
                ('intubed', models.BooleanField(default=False)),
                ('icu', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='diagnose.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnose.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnose.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnose.patient')),
            ],
        ),
    ]
